using System;
using System.Collections.Generic;
using Microsoft.Data.SqlClient;
using TicketSellingModule.Domain;

namespace TicketSellingModule.Repo
{
    public class FlightRepo
    {
        private readonly DbConnectionFactory _connectionFactory;
        public FlightRepo(DbConnectionFactory factory)
        {
            _connectionFactory = factory;
        }

        public List<Flight> GetAll()
        {
            List<Flight> flights = new List<Flight>();

            using (SqlConnection connection = _connectionFactory.GetConnection())
            {
                connection.Open();
                string sql = "SELECT id, date, flight_nr FROM Flights";

                using (SqlCommand command = new SqlCommand(sql, connection))
                {
                    using (SqlDataReader reader = command.ExecuteReader())
                    {
                        while (reader.Read())
                        {
                            Flight flight = new Flight();
                            flight.Id = reader.GetInt32(0);
                            flight.Date = reader.GetDateTime(1);
                            flight.FlightNumber = reader.GetString(2);

                            flights.Add(flight);
                        }
                    }
                }
            }
            return flights;

        }

        public int Add(Flight flight)
        {
            using (SqlConnection connection = _connectionFactory.GetConnection())
            {
                connection.Open();
                string sql = "INSERT INTO Flights (route_id, date, runway_id, gate_id, flight_nr) OUTPUT INSERTED.id VALUES (@route_id, @date, @runway_id, @gate_id, @flight_nr)";


                using (SqlCommand command = new SqlCommand(sql, connection))
                {
                    command.Parameters.AddWithValue("@route_id", flight.RouteId);
                    command.Parameters.AddWithValue("@date", flight.Date);
                    command.Parameters.AddWithValue("@runway_id", flight.RunwayId);
                    command.Parameters.AddWithValue("@gate_id", flight.GateId);
                    command.Parameters.AddWithValue("@flight_nr", flight.FlightNumber); 

                    // ExecuteScalar gets the new ID generated by the database
                    return (int)command.ExecuteScalar();
                }
            }
        }

        public Flight GetById(int id)
        {
            Flight flight = null; // Start with null in case we don't find it

            using (SqlConnection connection = _connectionFactory.GetConnection())
            {
                connection.Open();
                string sql = "SELECT id, date, flight_nr FROM Flights WHERE id = @Id";

                using (SqlCommand command = new SqlCommand(sql, connection))
                {
                    command.Parameters.AddWithValue("@id", id);

                    using (SqlDataReader reader = command.ExecuteReader())
                    {
                        // We use 'if' instead of 'while' because there should only be one match
                        if (reader.Read())
                        {
                            flight = new Flight();
                            flight.Id = reader.GetInt32(0);
                            flight.Date = reader.GetDateTime(1);
                            flight.FlightNumber = reader.GetString(2);
                        }
                    }
                }
            }
            return flight; // Returns the flight, or null if the ID didn't exist
        }

        public List<Flight> GetFlightsByRoute(int routeId)
        {
            List<Flight> flights = new List<Flight>();

            using (SqlConnection connection = _connectionFactory.GetConnection())
            {
                connection.Open();

                // We use the WHERE clause to let SQL Server do the filtering
                string sql = "SELECT id, route_id, date, runway_id, gate_id, flight_nr FROM Flights WHERE route_id = @route_id";

                using (SqlCommand command = new SqlCommand(sql, connection))
                {
                    // Securely pass the ID from the Service into the SQL query
                    command.Parameters.AddWithValue("@route_id", routeId);

                    using (SqlDataReader reader = command.ExecuteReader())
                    {
                        while (reader.Read())
                        {
                            Flight flight = new Flight();

                            // The numbers match the exact order of the SELECT string above
                            flight.Id = reader.GetInt32(0);
                            flight.RouteId = reader.GetInt32(1);
                            flight.Date = reader.GetDateTime(2);
                            flight.RunwayId = reader.GetInt32(3);
                            flight.GateId = reader.GetInt32(4);

                            // Using index 5 because it is the 6th item in the list
                            flight.FlightNumber = reader.GetString(5);

                            flights.Add(flight);
                        }
                    }
                }
            }

            return flights;
        }

        public void Update(Flight flight)
        {
            using (SqlConnection connection = _connectionFactory.GetConnection())
            {
                connection.Open();
                string sql = "UPDATE Flights SET route_id = @route_id, date = @date, runway_id = @runway_id, gate_id = @gate_id, flight_nr = @flight_nr WHERE id = @id";

                using (SqlCommand command = new SqlCommand(sql, connection))
                {
                    command.Parameters.AddWithValue("@date", flight.Date);
                    command.Parameters.AddWithValue("@flight_number", flight.FlightNumber);
                    command.Parameters.AddWithValue("@id", flight.Id);

                    // ExecuteNonQuery is used when we don't need to read data back, just change it
                    command.ExecuteNonQuery();
                }
            }
        }

        public void Delete(int id)
        {
            using (SqlConnection connection = _connectionFactory.GetConnection())
            {
                connection.Open();
                string sql = "DELETE FROM Flights WHERE id = @id";

                using (SqlCommand command = new SqlCommand(sql, connection))
                {
                    command.Parameters.AddWithValue("@id", id);
                    command.ExecuteNonQuery();
                }
            }
        }

    }

}